### ISSUE TITLE
Thread local loggers

### ISSUE THREAD

**Issue by arthurprs** [dpc/slog-rs#10]
I was wondering if we could have some sort of thread local logger (possibly adaptors for coroutine local as well), this way you wouldn't have to pass the logger around in most cases, making the crate much more ergonomic. 

It wouldn't work for all occasions, granted, but I can see it being very useful in a lot of cases.

**Comment by dpc** [comment]
Hmm...

So loggers can be used as immutable, are `Sync+Send`, so I believe they could be put into a global, and have a closure that prints some values from thread-local variables.

One could also store them in thread-local itself, pass to a spawned thread and save there, I believe.

I haven't really though about it yet and I'm open for feedback and ideas.

**Comment by dpc** [comment]
I have published examples of thread-local handling. (with some comments in the header). I'm still open for discussion on improvements.

**Comment by dpc** [comment]
Closing for now. No immediate action that I see.
