### ISSUE TITLE
`SwitchOnSignal` drain.

### ISSUE THREAD

**Issue by dpc** [dpc/slog-rs#16]
A drain handling signal by switching a drain. That would be useful for production debugging, as described in the README:

* drains are run-time swappable - Send a signal to your program and start logging everything to a file for run-time production debugging. Send another one when you're done to return to normal operation. Build your own flexible scenarios easily.

**Comment by 3Hren** [comment]
Just provide a method to reset loggers - that's enough. Maybe with an example.

Signal handling is very intimate place and should be only performed in applications - not libraries.

**Comment by dpc** [comment]
I'm thinking about he drain that exposes an atomic, that can be changed from outside, changing the sub-drain to route the messages to.

**Comment by dpc** [comment]
Done with http://dpc.pw/slog-rs/slog/drain/struct.AtomicSwitchCtrl.html

I should write an example that actually uses it in signal handle.

**Comment by dpc** [comment]
Added `examples/signal.rs`
