### ISSUE TITLE
Optimize performance

### ISSUE THREAD

**Issue by dpc** [dpc/slog-rs#19]
https://github.com/dpc/slog-rs/wiki/Bench-log

Ideas:

* [x] `&'a str` in RecordInfo`
* [x] static dispatch - `39e6b5e`
* [x] measure perf of closure-values
* [x] stdlog not to allocate String
* [x] `Arc` chaining instead of copying in Logger hierarchies?
* [x] closure-values not to allocate anything - implement `SerializeKey` for `Fn(&RecordInfo, mut io::Writer)` ? so the value can output itself without returning?
* [x] use the same `feature` that standard `log` uses to remove logging statesments at compile time. Now that macros are being used, this should work smoothly.

**Comment by 3Hren** [comment]
Where are benchmarks?

**Comment by 3Hren** [comment]
> `&'a str` in RecordInfo

Maybe `Cow<'a, str>` is better?

**Comment by dpc** [comment]
Hmm... `msg` is kind of expected to be just string literal, and `Cow` causes a `if` every time it's used, no?

**Comment by dpc** [comment]
I forgot to commit some files. :D Should be there now.

**Comment by 3Hren** [comment]
> Hmm... msg is kind of expected to be just string literal, and Cow causes a if every time it's used, no?

Of course.

I'm not sure about how you obtain those string. In blacklog there was a choice what to save: a raw string literal, which does not require formatting (use &str) or a result of `format!("{}", Arguments<'a>)`, which is String. There `Cow` perfectly fit.

Did you think about integration with Rust formatting ecosystem?

**Comment by 3Hren** [comment]
Because there - https://github.com/dpc/slog-rs/blob/master/crates/stdlog/src/lib.rs#L61 - arguments are evaluated every time, even if an event will be filtered out.

**Comment by dpc** [comment]
Now you have make me thing about it. Simplest solution that I come up with, ATM is  `Drain` to have two functions: one for `&str`, one for `Arguments`. Each drain that had to convert `Arguments` into `string` would actually pass it forward via `fn log(&'str msg...)` so everything above it, doesn't have to format it again. A bit more code for each drain, but avoids any unnecessary operations at runtime.

This would also allow taking msg that would have formatting in it, if necessary. Though it seems to me, that structured logging avoids need for `format!` and users should rather put really simple `msg`-s (`&'static str`), as anything "variable" should be a key-value.

What do you think?

**Comment by 3Hren** [comment]
I think formatting is important.

Actually creating `Arguments<'a>` from string literal without other arguments is cheap. You can always pass `Arguments<'a>` and, since, you format in the caller thread into `Vec<u8>` do it with `write!(vec, "{}", args)` as you do here for example: https://github.com/dpc/slog-rs/blob/master/crates/json/src/lib.rs#L184.

**Comment by dpc** [comment]
The biggest problem is that `Argument<'a>` introduces another lifetime that break closures as values.

**Comment by 3Hren** [comment]
Just as replacing `String` with `&'a str` in the `RecordInfo`, isn't it?

**Comment by dpc** [comment]
There was so much problem with it... Too long to describe now. After I got it to work, it does not appear that bad.

I actually got it work, but with `&'a str`.

It appears to me that `Arguments<'a>` support for `msg` is unnecessary. In  `stdlog` I'll just pass `Arguments` as a closure value under different key so it get evaluated only if it was used. Since anyone can write any custom  formatter etc. with a bit of work it's possible to get any actual output with this scheme, so why complicate and slow down the common case (just using the string literal)?

The way I think about: if anyone really, really needs `format_args!` it's possible with combination of:

* building own macro
* using closure-values
* using `format!` manually

I need to benchmark closure values, and see if there's no fundamental problems with their performance.

**Comment by 3Hren** [comment]
Disagree, but as your wish.

**Comment by dpc** [comment]
I'm still open to being convinced, if you feel strongly about it, and if more people will voice an opinion in favour of changing it, I probably will. 

After I got `&'a str` to work it shouldn't be too hard to get `&'a Arguments<'a>` to work, so I might try just to see the performance of `format_args!("literal") `.

**Comment by dpc** [comment]
Also, it seems to me that current version of closure values is sub-optimal. Eg. sometimes it needs to allocate String etc. since it has to return the value (so it can't return newly created `&str` (or even `&str` from `RecordInfo`).

Maybe passing it some  handle that would allow it to call a method to serialize a value would help?

**Comment by dpc** [comment]
While thinking about #16 I've noticed that switching drains at run-time is not something everyone needs, while it prevents optimizations. Removing it to be a separate drain, was a big benchmark win.

**Comment by dpc** [comment]
OK, so `fmt::Argument<'a>` is supported after all.

**Comment by dpc** [comment]
It's done.
