### ISSUE TITLE
Unable to log any trace output

### ISSUE THREAD

**Issue by CraZySacX** [dpc/slog-rs#44]
No matter how I configure my Cargo.toml, I am unable to produce any trace output.

The latest attempt is below:

```
[dependencies.slog]
version = "1.0.0-alpha6"
default-features = false
features = ["release_max_level_trace", "max_level_trace"]
```

After digging around a bit I believe the culprit is Cargo not honoring the default-features = false flag.

It seems that all the features are enabled (in this case, "release_max_level_info, release_max_level_trace, max_level_debug, and max_level_trace").   Due to the if clause in lib.rs, and a normal debug build, "max_level_debug" is always hit, and trace can never be enabled.

**Update**
Running ```cargo build --verbose``` shows the following passed to rustc (and includes all 4 dependencies):

```
     Running `rustc /home/jozias/projects/slog-rs/src/lib.rs --crate-name slog --crate-type lib -g --cfg feature=\"max_level_trace\" --cfg feature=\"release_max_level_info\" --cfg feature=\"max_level_debug\" --cfg feature=\"default\" -C metadata=b5fec68b10428a12 --out-dir /home/jozias/projects/trace/target/debug/deps --emit=dep-info,link -L dependency=/home/jozias/projects/trace/target/debug/deps`
```

So this looks like a bug in Cargo where it isn't removing the default dependencies even when ```default-features = false``` is used.

I'm going to open an issue on the cargo project.

**Comment by CraZySacX** [comment]
For reference, here is the issue in the cargo project:

https://github.com/rust-lang/cargo/issues/3090

**Comment by dpc** [comment]
Good find. Thanks for report.
