### ISSUE TITLE
Derive or implement `Debug` for `Logger`

### ISSUE THREAD

**Issue by tomprogrammer** [dpc/slog-rs#49]
`Logger`s should be stored in the structs their context is associated with. Since `Logger` doesn't implement `Debug` this imposes a limitation on these structs.

How should the output of `Debug` look? The connected drain and a list of owned values are available in the loggers. I think printing the list of owned values is sufficient to identify the logger.

**Comment by dpc** [comment]
Good idea.

**Comment by dpc** [comment]
I am thinking about printing just keys. Something like `slog::Logger: [key1, key2, key3]`, but without serializing values. Values can potentially be lazy, costly to calculate, or even have side effects.

Sounds reasonable?

**Comment by tomprogrammer** [comment]
Yes, absolutely.
