### ISSUE TITLE
StdLog doesn't pass key => value from inside log messages with env_logger

### ISSUE THREAD

**Issue by Emilgardis** [dpc/slog-rs#59]
I'm currently trying to implement stdlog for [Amethyst](https://www.github.com/amethyst/amethyst) for optional slog support for a binary. To enable this, I'm using the 

    struct Foo {
        logger: logger.unwrap_or(slog::Logger::root(slog_stdlog::StdLog.fuse(), o!()))
    }

method described in [crates/example-lib](../blob/master/crates/example-lib/lib.rs) However, when a binary doesn't use a slog drain, but env_logger, messages that should look like this with env_logger (and does with slog)

    ERROR:my:library:source: error message here, errorid: 405, cause: foo

looks like

    ERROR:my:library:source: error message here

skipping the information that should be delivered with `error!(self.logger, "error message here"; "errorid" => error_id, "cause" => cause);`

**Comment by dpc** [comment]
Thanks for report! I've just missed that. :( . Should be fixed now - please confirm if it works for you as expected. I need to optimize in https://github.com/dpc/slog-rs/issues/60, and if it does, I'll publish new version.

**Comment by Emilgardis** [comment]
LGTM! Thank you!
