### ISSUE TITLE
Bunyan format

### ISSUE THREAD

**Issue by passcod** [dpc/slog-rs#8]
Would be nice to have [Bunyan](https://www.npmjs.com/package/bunyan) output format, so we can keep using the same rich filtering and analysis tools across languages.

**Comment by dpc** [comment]
Looks good. I guess it could be a simple wrapper over `drain::Json`.

**Comment by dpc** [comment]
Implemented in https://github.com/dpc/slog-rs/commit/aefc00eac920ace63727f67370124a90e4beed9b

I did not try it with anything serious yet. I'd appreciate letting me know if there are any problems with it.

**Comment by passcod** [comment]
Awesome! :)
